### ISSUE TITLE
Feature: Refactor this to use fs.openDir in future and not fs.readdir

### ISSUE THREAD

**Issue by frank-dspeed** [paulmillr/readdirp#105]
NodeJS > 12.11.1 will have async readdir support Landed in cbd8d71 ( nodejs/node@cbd8d71 ) as fs{Promises}.opendir(), which returns an fs.Dir, which exposes an async iterator.

to stay compatible we could implament it with the same stream interface and simply check if fs.openDir is there if not fallback to existing implamentation. 

# This is a lobby Request <3 by the microsoft/vscode community
- https://github.com/microsoft/vscode/issues/82116

**Comment by paulmillr** [comment]
easy

**Comment by paulmillr** [comment]
Here is the simplest implementation of the approach using nodejs v12.12. Performance numbers are not amazing — it's actually 10% slower. Which makes opendir only useful for huge directories.

We will need to release new major ver of readdirp for that, since node v8 doesn't support async iterators.

```js
const {opendir} = require('fs').promises;
const sysPath = require('path');

async function* readdirp(parentPath) {
  const dir = await opendir(parentPath);
  for await (const dirent of dir) {
    const path = sysPath.join(parentPath, dirent.name);
    if (dirent.isDirectory()) {
      yield* readdirp(path);
    } else {
      yield path;
    }
  }
```

**Comment by paulmillr** [comment]
See branch **v4** for implementation: https://github.com/paulmillr/readdirp/tree/v4

Execute `node examples/list`, ensure to pass big directory there.

1. v4 branch ditches readable stream in favor of async generators (node 10+).
2. This allows to speed-up a file tree of 45k entries from 1.6 sec to 500ms (3x).
3. `opendir` works, you'll need node 12.12, it's 3x slower than `readdir` — MEH! It's as slow as current readdirp-v3.

**Comment by yisibl** [comment]
Hi, @paulmillr Why is opendir slower instead?

**Comment by paulmillr** [comment]
@yisibl ?

**Comment by yisibl** [comment]
> opendir works, you'll need node 12.12, it's 3x slower than readdir — MEH! It's as slow as current readdirp-v3.

**Comment by paulmillr** [comment]
What is the question? Open dir is 3x slower. Why is it slower? I don't know. Shitty node.js implementation.
