### ISSUE TITLE
npm install warning

### ISSUE THREAD

**Issue by XhmikosR** [paulmillr/readdirp#123]
It seems typescript is missing from devDependencies?

https://github.com/paulmillr/readdirp/runs/272245666#step:4:6

**Comment by XhmikosR** [comment]
BTW this is the slowest part on CI; dtslint downloads all types every time.

**Comment by paulmillr** [comment]
Yeah, that’s why I don’t like it.

**Comment by paulmillr** [comment]
Perhaps we do dtslint only when the file was changed, or something like that. Or on release only.

**Comment by XhmikosR** [comment]
But then it means that a release would have been made and it might have broken types.

Unless you follow a specific branch scheme before releases, say `release-*` or similar, then we could run it separately. Still, since I'm not familiar with dtslint, I'm not sure if we need to add typescript to devDependencies.
