### ISSUE TITLE
Use fs.Dir

### ISSUE THREAD

**Issue by Fishrock123** [paulmillr/readdirp#135]
[`fs.Dir` on the Node docs](https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_class_fs_dir)

The perf issues mentioned in https://github.com/nodejs/node/pull/30114 should now be alleviated mostly by default, and if you want to optimize, an option for the number of buffered entries can be specified as of https://github.com/nodejs/node/pull/30114, to be in the next release.

**Comment by paulmillr** [comment]
#105
