### ISSUE TITLE
Typings for `directoryFilter` option are wrong

### ISSUE THREAD

**Issue by cedx** [paulmillr/readdirp#145]
The `directoryFilter` option seems to accept the same parameters as the `fileFilter` option.

In the `README.md` file, we can read: `directoryFilter: ['!.git']`, that is an array of strings.
But the TypeScript typings only allow: `(entry: EntryInfo) => boolean`.

It should probably be: `string | string[] | ((entry: EntryInfo) => boolean)`

**Comment by paulmillr** [comment]
Go ahead and change it!
