### ISSUE TITLE
Doesn't follow symbolic link to directories

### ISSUE THREAD

**Issue by znarf** [paulmillr/readdirp#150]
Currently, the library is properly following symbolic link to files but it's not properly following symbolic link to directories.

It's considering any symbolic link as files: https://github.com/paulmillr/readdirp/blob/master/index.js#L202

**Comment by bpasero** [comment]
@znarf @paulmillr trying to understand the consequence of this change for `chokidar`: I just verified that I see file events (on macOS) for a symlinked folder when I change files within even with an older version of `chokidar`, so it seems to me that `chokidar` always supported this? Then I do not understand what impact this change has on `chokidar`?
