### ISSUE TITLE
Load picomatch lazily

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/readdirp#158]
Picomatch seems to account for most of the loading time of readdirp:

![image](https://user-images.githubusercontent.com/1812093/79167845-532fa880-7de0-11ea-9ca7-f5b5e77fd2e8.png)

I was looking into potential optimizations, and in my app I don't need to pass a glob to readdirp so still having to pay the cost for loading picomatch seems nonoptimal.

I think picomatch should be loaded lazily only if/when needed.

**Comment by paulmillr** [comment]
Do you really care about 2ms? Why?

**Comment by fabiospampinato** [comment]
Milliseconds add up 🤷‍♂️ 2ms aren't the end of the world, but it could take maybe 10ms in a low end device, and 20 of these tiny optimizations will add up to 40~200ms eventually which at startup especially will make a difference.

I can submit a PR for this if you like.

**Comment by paulmillr** [comment]
The real question here is why are you using readdirp in a browser. Eliminating it from your build would achieve the result, no?

**Comment by fabiospampinato** [comment]
It's a browser but it's a node.js app at the same time, i.e. I'm using [Electron](https://github.com/electron/electron).

**Comment by lydell** [comment]
FYI picomatch was removed in https://github.com/paulmillr/readdirp/commit/703dee9f823f74fd990b503df52652f397759b1f (not released yet)
