### ISSUE TITLE
Warn instead of error for recursive detection

### ISSUE THREAD

**Issue by ath0mas** [paulmillr/readdirp#168]
As I am willing to update/fork [rm-modules](https://github.com/hughsk/rm-modules) for the possible _Out of memory_ I am facing too (https://github.com/hughsk/rm-modules/issues/5), updating **readdirp** with version 3.5 and its "infinite loop" fix seems perfect,
> 3.5 (Oct 13, 2020) disallows recursive directory-based symlinks. Before, it could have entered infinite loop.

but Should it be possible to not destroy and exit on error in this case? like adding recursive to NORMAL_FLOW_ERRORS

In _rm-modules_ case, the expected behavior would be to continue and process all but the problematic entry.

**Comment by paulmillr** [comment]
perhaps. pull request for the change would be reviewed
