### ISSUE TITLE
bigint param not work

### ISSUE THREAD

**Issue by hughdev** [paulmillr/readdirp#183]
/**
 * @typedef {Object} ReaddirpArguments
 * @property {Function=} fileFilter
 * @property {Function=} directoryFilter
 * @property {String=} type
 * @property {Number=} depth
 * @property {String=} root
 * @property {Boolean=} lstat
 * @property {Boolean=} bigint
 */

    if (wantBigintFsStats) {
      this._stat = path => statMethod(path, { bigint: true });
    } else {
      this._stat = statMethod;
    }

"readdirp": "^3.6.0",
allwas bigint = true

like this code 
const files = await readdirp.promise('test/dir', {
            bigint: false,
          })

**Comment by hughdev** [comment]
@paulmillr

**Comment by paulmillr** [comment]
we don't have option bigint: true/false. Bigint is automatically used on windows and not used on non-windows.

**Comment by hughdev** [comment]
hello. why? return bigint JSON.stringify() doesn't know how to serialize a BigInt.when i run windows.
can u help how to solve it .

options there any problem writing here?

**Comment by hughdev** [comment]
hello, whty not support options? bigint?
@paulmillr

**Comment by paulmillr** [comment]
#100
