### ISSUE TITLE
Wrong types? result should be EntryInfo[], but is typed as string[]

### ISSUE THREAD

**Issue by KillerCodeMonkey** [paulmillr/readdirp#201]
Hello,

with the latest changes the the readdirpPromise method is typed to return only an array of strings:

VSCode says:

```TS
readdirpPromise(root: Path, options?: Partial<ReaddirpOptions>): Promise<string[]>
```

Is this expected?

**Comment by paulmillr** [comment]
No

**Comment by KillerCodeMonkey** [comment]
@paulmillr i try to create PR in the next hours. fixing some typing.
there is even something wrong with the filter types.

you are generating the typings by the default values of the ReaddirpOptions, but then you are not able to pass a string or glob pattern to the filter methods.

i will try to fix those things as well
