### ISSUE TITLE
Implement backpressure

### ISSUE THREAD

**Issue by toddself** [paulmillr/readdirp#31]
We've got some projects at work where we're crawling a very large directory structure and running a time-consuming process on each file found in those directories (reading and parsing a proprietary binary file format, generating our file format from it and then indexing it).

The directory structure is too large to use the non-streaming API for readdirp, so we're streaming and then actually forking new node processes for each file (keeping a maximum concurrency of 2 forked processes).  When we hit max concurrency we call `stream.pause()`.

However this just causes readdirp to cache the directory entries rather than pause walking the filesystem -- since processing these files takes a good bit of time (multiple seconds for each one), we're unable to keep up with readdirp and eventually the box runs out of RAM.

It looks like it could be implemented buy adding a `setTimeout`, `setImmediate` or `process.nextTick` call into `readdirRec` if the stream is currently paused, causing it to call it again with the same arguments rather than continue parsing.

Is this an approach you'd be interested in accepting a PR for? do you have another idea on how this could be implemented? (This is the first time I've dug into the source for this.)

**Comment by thlorenz** [comment]
Sounds complex, but if you can get it to work and pass all tests I'd pull it in.
Ideally we'd keep the current behavior as a default (worse for memory, better for performance) and turn yours on via a flag.

In that case just run all tests with your flag on and they should pass.

**Comment by toddself** [comment]
Having problems with testing this due to #29; patch is pretty simple -- if the state is paused it finishes up what it was actively working on, queuing the results from that.

When it hits a new `readdirRec` it checks the paused state -- if paused it does a `setImmediate` to call and check the state again with the original arguments.

**Comment by toddself** [comment]
Although how do you feel about this:
`setImmediate(readdirRec.bind.apply(null, [null].concat([].slice.call(arguments))))`

**Comment by thlorenz** [comment]
Looks really ugly :P
At conference right now, so really limited bandwidth (literally on 2G) to deal with this.
Just give it a shot and we can discuss/fix things from there.

Hopefully @es128 can provide some feedback as well.

**Comment by es128** [comment]
For the moment I'll just echo that I think you should just do whatever you need to do to get it working, open a PR early for feedback (don't necessarily need to wait until it's ready), and then afterward we can look at whatever refactoring it's going to need. 

Not sure I know of any cleaner way to do what you're showing in that little snippet, but perhaps it would be useful to see the rest of the context. You could maybe write an actual `function` rather than using `.bind()`, but it probably wouldn't help much, you'd just end up doing similar things inside with a `.apply()`

As for #29, if you haven't already then just pin to tap@1.3.2 where it works, and then you'll be able to more easily see what impact your changes are having. Or are the failures exposed by later version of tap the same thing getting in the way when you start implementing synthetic deferrals?

**Comment by toddself** [comment]
Ah. ok. Yes, `tap@1.3.2` works correctly with testing.  Thank you @es128 and @thlorenz! I'll get to working on the testing for this (and making that `setImmediate` call look a little less funky)

**Comment by toddself** [comment]
Testing this is actually much harder than I expected -- what I really need is to verify that `_processEntry` isn't called but I can't access the prototype for `ReaddirpReadable` since that object isn't exported (only instances of it), and the export from `readdirp.js` is the `stream` object rather than the underlying API calls.

I might need to expose the `ReaddirpReadable` object in order to verify this change unless someone can come up with a better way to test this?  

There is already a test to verify the stream doesn't emit during `pause`, but I need to verify it's still not just reading the disk as well.

**Comment by es128** [comment]
I think you'll need to unit test stream-api separately.

But also in case you weren't aware of modules like https://github.com/thlorenz/proxyquire and https://github.com/jhnns/rewire - they may be able to help you get to the unexposed objects you need to inspect or mock without unnecessarily exposing them in the regular module code.

**Comment by toddself** [comment]
PR here https://github.com/thlorenz/readdirp/pull/32
