### ISSUE TITLE
v2.1.0 maxes out CPU and doesn't finish

### ISSUE THREAD

**Issue by davej** [paulmillr/readdirp#48]
I am using `readdirp` with a little library called [`baconize`](https://github.com/davej/baconize) and it fails consistently with certain combinations of files. It always gets to the last file and then just maxes out the CPU and doesn't finish. If I downgrade `readdirp` to 2.0.1 then it succeeds every time.

This only seems to occur on sufficiently complicated directories and it wasn't caught by the tests on baconize.

I can delve in and try to get more info if you like but considering the small delta between 2.0.1 and 2.1.0, I thought it might be possible for someone to figure out what might be causing this.

**Comment by dypsilon** [comment]
Thank you for this bug report. I had a similar case which was caused by the stream not ending. Downgrading to 2.0.1 helped fix the problem.

**Comment by thlorenz** [comment]
Interesting, main change that happened in between those versions is [this commit](https://github.com/thlorenz/readdirp/commit/45de852cc876794a54dbc40b983ea8a1bb534209).

@toddself do you have an idea how this might be related?

**Comment by toddself** [comment]
my initial guess is that it's somehow stuck in a paused state -- it intentionally loops asynchronously when paused.

@davej any other information on how to repo this would be super helpful!  i can try to dive into this later today

**Comment by davej** [comment]
I've since switched to a different library and this was a long time ago so I'm not able to provide any insight. Sorry.
