### ISSUE TITLE
faux stream

### ISSUE THREAD

**Issue by leviwheatcroft** [paulmillr/readdirp#50]
I get the feeling readdirp is more like an event emitting buffer than a stream, and this masquerade is the underlying issue behind all current issues, some of which are significant.

The basic idea of a readable stream is to generate & provide data from an underlying source *as it's required* by a consumer.

The core principle of readdirp is to walk the fs and buffer the objects, emitting events as each is identified. Notably the readdirp stream implementation:

 * sets [highWaterMark to infinity](https://github.com/thlorenz/readdirp/blob/master/stream-api.js#L22) which is the antithesis of a stream.
 * [noops _read](https://github.com/thlorenz/readdirp/blob/master/stream-api.js#L55) which is usually used to notify the stream that it needs to harvest data from the underlying source. There's no use for it in this implementation because readdirp just keeps reading until paused.

That might be fine because it still kind of quacks like a stream, but because the core code wasn't designed to behave as a stream, enhancements to better emulate stream-like behavior will cause problems. 

Case in point, in order to emulate backpressure without using _read (because that would be very difficult with this code base) PR  #32 implements [a setImmediate loop](https://github.com/thlorenz/readdirp/pull/32/files#diff-ea4dc01f5ee19cf7877a04c762a4646eR211) when the stream is paused (not being consumed). That *may* be satisfactory if your consumer is cpu intensive. If your consumer is not cpu intensive (like working with a http api, uploading files.. whatever) then this setImmediate loop is going to consume 100% cpu time while it's doing nothing waiting to unpause. This particular issue is causing #48.

The other open issues #35 (parallelism) and #31 (backpressure) are clearly related to these problems.

**Comment by paulmillr** [comment]
@leviwheatcroft what is your main idea? What should we do exactly?

**Comment by paulmillr** [comment]
WIP in gh-54
