### ISSUE TITLE
Make readdirp a real stream; to be able to scan 100,000+ files

### ISSUE THREAD

**Issue by vasyl-shumskyi** [paulmillr/readdirp#54]
Hello,

I've tried to scan large directory witch contains 262,839 files with `readdirp` but got 

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

```
$ time find ~ -type f | wc -l
  262839
find ~ -type f  0.28s user 4.12s system 55% cpu 7.911 total
```

After tweaking node memory consumption via ` --max_old_space_size` I had to abort the running command because of resources overusing:

```
$ time node --max_old_space_size=4000 readdirp.js
^C
node --max_old_space_size=4000 readdirp.js  156.57s user 497.05s system 81% cpu 13:21.85 total
```

Script looks like the following: 
```
const readdirp = require('readdirp');
const fpath = '/Users/Username'
let count = 0

console.time(fpath)

const settings = {
    root: fpath,
    entryType: 'files',
    //lstat: true
};

readdirp(settings)
   .on('data', function (file) {
        count++
    })
.on('warn', function(warn){
    console.warn("Warn: ", warn);
})
.on('error', function(err){
    console.error("Error: ", err);
})
.on('end', function(){

    console.log(count, 'files')
    console.timeEnd(fpath)
});
```

What is the proper way to scan such a big amount of files with `readirp`? 

Kindly assist

**Comment by yoshuawuyts** [comment]
heh, looks like you ran into a memory leak somewhere - a good way to figure out what's blocking you might be to attach the debugger to figure out what's going on

**Comment by yoshuawuyts** [comment]
Or alternatively, run 0x https://www.npmjs.com/package/0x

**Comment by vasyl-shumskyi** [comment]
Yeah, that's certainly  memory leak. It happens because of crazy large amount of files (262,839)

The the question was how to properly scan such a big amount of files?

**Comment by thlorenz** [comment]
Maybe you could give glob a try. Could be that works better for you ...

**Comment by rolanday** [comment]
@thlorenz , are you suggesting by your comment that readdirp should not be used in scenarios where search potentially involves a large number of files?

Such a scenario is the very thing that lead me to evaluate readdirp; however, I cannot complete a scan of my user directory (simple test case to eval) before running out of memory, and increasing memory the limit lets the readdirp progress a only little further before it hangs at around 550k files found (and cpu running hot).

I am using the recommended stream example exactly as provided w/ exception of simple counter added :

```
var readdirp =  require('readdirp');

let i = 0;
var settings = {
    root: '/users/roland',
    entryType: 'files'
};

readdirp(settings)
    .on('warn', function (err) {
        console.error('something went wrong when processing an entry', err);
    })
    .on('error', function (err) {
        console.error('something went fatally wrong and the stream was aborted', err);
    })
    .on('data', function (entry) {
        console.log('%s, %d', entry.path, i++);
        // process entry here
    });
```

Thanks for your contribution and appreciate and insights or recommendations, including advising if my scenario is outside design parameters for readdirp.

**Comment by paulmillr** [comment]
@rolanday we're fixing this now — a PR is coming soon

**Comment by rolanday** [comment]
That's great to hear. If you can kindly update this issue thread once fixed that would be great. Thanks!

**Comment by kmalakoff** [comment]
I have recently made some improvements to https://github.com/kmalakoff/walk-filtered to try to address large number of files:

- global concurrency - it used to be per directory, but now is across all file system entries
- memory footprint - sharing references to path strings

I haven't updated the readdirp wrapper: https://github.com/kmalakoff/readdirp-walk and troubleshot the tests, but could if you are interested assuming readdirp is a valuable abstraction still.

Also, I've added a promises implementation to support async / await, but that is more for modern versions of Node.

**Comment by rolanday** [comment]
> @rolanday we're fixing this now — a PR is coming soon

Hi there :-) Can we please get an update on PR to address issue? Thanks!!
