### ISSUE TITLE
Remove/Exchange usage of event-stream module in Readme.md

### ISSUE THREAD

**Issue by jhillejan** [paulmillr/readdirp#58]
Inside the Readme.md the event-stream module is being used, which contains malicous code in its latest versions. The usage should be exchanged with another way dealing with the streams.

Sources:
https://github.com/dominictarr/event-stream/issues/116
https://thehackernews.com/2018/11/nodejs-event-stream-module.html

**Comment by paulmillr** [comment]
Feel free to do it.

**Comment by jhillejan** [comment]
Hi Paul, the new version doesn´t compile. Please check again. Thanks.
