### ISSUE TITLE
In windows readdirp.statfn() may resolve multiple files with same inode

### ISSUE THREAD

**Issue by garu57** [paulmillr/readdirp#61]
Due to issue [#12115](https://github.com/nodejs/node/issues/12115) in node.js, `readdirp.statfn()` in windows can return a `stat` object with same inode for multiple files.

As per solution of the referred issue you should allow passing option `{bigint: true}` to `fs.stat()` and `fs.lstat()`.
Thanks.

**Comment by paulmillr** [comment]
We aren't using stat by default anymore.
