### ISSUE TITLE
Version 3.x stream interface not emitting warning event (and unhandled promise rejection warnings instead)

### ISSUE THREAD

**Issue by rolanday** [paulmillr/readdirp#75]
Repro steps using following sample code:

1. Create an empty folder in root directory to scan for files, and remove read perms like so:
```
$ mkdir noaccess
$ chmod -r noaccess
```
2. Then run following code from root of folder where noaccess directory was created:
```
const readdirp = require('readdirp');
readdirp('.', {
  alwaysStat: true,
})
  .on('data', (entry) => {
    const {path, stats: {size}} = entry;
    console.log(`${JSON.stringify({path, size})}`);
  })
  // Optionally call stream.destroy() in `warn()` in order to abort and cause 'close' to be emitted
  .on('warn', error => console.error('non-fatal error', error))
  .on('error', error => console.error('fatal error', error))
  .on('end', () => console.log('done'));
```

Expected behavior is for warn event to fire, as per documentation and v2.x behavior.

Actual is event does not fire and instead get unhandled promise rejection warning like so:
```
(node:43530) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, scandir '/Users/roland/source64/noaccess'
(node:43530) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:43530) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm running Node v10.15.3, macOS

**Comment by rolanday** [comment]
I took a closer look at this and the problem is two-fold:
1.  Not treating node access error (EACCES) as  normal flow error (i.e., isNormalFlowError doesn't return true for this case). IMO, should be treated as such and this was also the behavior for v2.x.

2. The following block of code is not emitting a warn for the case where isNormalFlowError === true.
```
    // To prevent race conditions, we increase counter while awaiting readdir.
    this.filesToRead++;
    try {
      files = await readdir(parentPath, this._readdir_options);
    } catch (error) {
      if (!isNormalFlowError(error)) throw error;
    }
    this.filesToRead--;
```
I updates a forked version to emit warn (and handle EACCES) and the code works, but I spent little more than 15 min looking on this so I'm most definiately not suggesting it's a proper fix.

```
    this.filesToRead++;
    try {
      files = await readdir(parentPath, this._readdir_options);
    } catch (error) {
      if (isNormalFlowError(error)) {
        // emitting warn event in-line here instead calling this._handleError (as
        // commented out below else done fires before warn.
        this.emit('warn', error); 
        // this._handleError(error);
      } else {
        throw error;
      }
    }
    this.filesToRead--;
```

**Comment by paulmillr** [comment]
yep — we'll need to fix this.

How is version 3 overall?

**Comment by rolanday** [comment]
Overall, definite improvement over 2.x. No issues w/ memory for me when large # of files, and a number of other improvements to the programming interface appreciated (such as moving root param out of options, and ability to suppress stat read for improved performance.

Thank you, thank you, thank you :-)

**Comment by paulmillr** [comment]
Landed in master.
