### ISSUE TITLE
warn event fires after end for stream interface

### ISSUE THREAD

**Issue by rolanday** [paulmillr/readdirp#78]
Related to [#75](https://github.com/paulmillr/readdirp/issues/75), warn fires after end on latest head version 3.0.0..

**Comment by rolanday** [comment]
Should also add, to repro scan an otherwise empty root except for single subdirectory that has its read perms removed, like so

```
- root. <== readirp this
     |- subdir <== chmod -r this
```
This will prevent issue from slipping by because there were other files remaining to be found after the warn'ed dir (or file), giving chance for warn to fire in time before close event.

**Comment by paulmillr** [comment]
try it.

**Comment by rolanday** [comment]
Fix works. Thank you!!
