### ISSUE TITLE
Deep symbolic link chain results in UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by rolanday** [paulmillr/readdirp#82]
Scanning homedir w/ alwaysStat=true results in the following error on my system (multiple occurrences):
```
(node:87488) UnhandledPromiseRejectionWarning: Error: ELOOP: too many symbolic links encountered, stat '/Users/roland/Movies/Untitled.fcpbundle/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache/.fcpcache'
(node:87488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```
I verified the symbolic link chain is present (and deep like shown).

macOS, node 10.15.1, readirp head version. Can be repro'd using standard streams sample documented by readme.

**Comment by paulmillr** [comment]
Try lstat: true

**Comment by rolanday** [comment]
> Try lstat: true

Didn't mention but I already did as much. Thanks for investigating.

**Comment by rolanday** [comment]
Thanks for 3.0.1 update. Working flawlessly for my needs, and much appreciate the contribution!!

w/o stats
153,141 files found in 8.7s

with: { alwaysStat: true,  lstat: true } options
153,141 files in 63.7s

So, YMMV depending, because for smaller sets I find 2x perf cost like the README suggest.

Interestingly., when I enable just alwaysStat (but not lstat) the same take a very long time until out of memory error. Just FYI as something might want to look into.

Thanks again!

-Roland.
