### ISSUE TITLE
bad release v3.0.1

### ISSUE THREAD

**Issue by Roms1383** [paulmillr/readdirp#90]
Hi @paulmillr I think you have a problem on your [latest release 3.0.1](https://github.com/paulmillr/readdirp/releases/tag/3.0.1) and some others : 

currently on your [master's index.js](https://github.com/paulmillr/readdirp/blob/master/index.js) the part of the code where the `directoryFilter` is evaluated is correct :
<img width="548" alt="Screen Shot 2562-06-02 at 23 31 23" src="https://user-images.githubusercontent.com/21016014/58764233-cba5c600-858e-11e9-8a35-9139eb0bb72f.png">
as in the method `normalizeFilter`, all `negative` should use `negative.some` instead of `negative.every` (I tested it locally).

but when installing several releases from NPM (so far I've tried `3.0.1`, `3.0.0` and `2.0.1`) the code installed contains `negative.every`, causing the `directoryFilter` to only work with a single entry (e.g. `['!.git']`), while failing with many entries (e.g. `['!.git', '!node_modules']`).
<img width="1440" alt="Screen Shot 2562-06-02 at 23 45 21" src="https://user-images.githubusercontent.com/21016014/58764396-a5812580-8590-11e9-8b33-070e29a31750.png">

I can't open a PR as your code on master is correct, it looks like it's more a problem happening on releasing.

Hope this helps 😊

**Comment by Roms1383** [comment]
p.s : if you need some help for refactoring and adding unit-tests, travis and semantic-release I can help

**Comment by Roms1383** [comment]
p.s : it's also related to my comment [here](https://github.com/paulmillr/readdirp/issues/1#issuecomment-497638445)

**Comment by paulmillr** [comment]
pushed
