### ISSUE TITLE
readdirp depth issue

### ISSUE THREAD

**Issue by jazkh** [paulmillr/readdirp#91]
By default readdirp does depth: 1 
If I change this to depth: 0  then readdirp does not show the sub-directory name. I don't want to list sub-directory files but only sub-directories name. How can I achieve this?

**Comment by TotallyInformation** [comment]
I also have this issue. depth=0 ignores the top-level folders.

**Comment by TotallyInformation** [comment]
Still happening with v3.1.3

**Comment by ronag** [comment]
@TotallyInformation Is this still an issue?

**Comment by TotallyInformation** [comment]
Yes, I'm afraid so unless there is another update beyond 3.1.3 that I haven't tested.

**Comment by TotallyInformation** [comment]
Appears to be fixed in v3.3.0 so can probably be closed now.
