### ISSUE TITLE
Add File filter

### ISSUE THREAD

**Issue by RamK777** [paulmillr/readdirp#94]
I added the file filter 
`readdirp('.', {fileFilter: '!image001.png', alwaysStat: true})
  .on('data', (entry) => {
    const {path, stats: {size}} = entry;
    console.log(`${JSON.stringify({path, size})}`);
  })`

my case is, if that file image001.png present two or more different nested directories means and i had to skip that file from only one location means , how to specify that particular file from particular location ???? 

i tried like this below code but not works, i think readdirp internally compares with file name only not path using picomatch.

``readdirp('.', {fileFilter: '!D:fileuploader\NEW_TEST\image001.png', alwaysStat: true})
  .on('data', (entry) => {
    const {path, stats: {size}} = entry;
    console.log(`${JSON.stringify({path, size})}`);
  })``

Is there any way to do it  ???

**Comment by paulmillr** [comment]
`fileFilter: (path) => {return path !== 'D:\fileuploader\NEW_TEST\image001.png'}`
